### ISSUE TITLE
Clarify the meaning of fields in `Timezone`

### ISSUE THREAD

**Issue by FeldrinH** [twitchax/rtz#4]
The [documentation for `Timezone`](https://docs.rs/rtz/latest/rtzlib/base/types/struct.Timezone.html) is very terse and doesn't really explain what any of the fields mean. I presume these fields are taken from the Natural Earth dataset, but I couldn't find the relevant documentation for the dataset online.

It would be useful if either the meaning of these fields was clarified or if the docs of this crate linked to relevant documentation from Natural Earth that explains their meaning.

Some of the specific questions I had:
* Is `friendly_name` the IANA TZ identifier?
* Why is `friendly_name` an `Option`? What does it mean when it is `None`?
* What is `zone_str`? Is it just `zone_num` as a string and if so why does it's example value differ from `zone_num`?
* Why is `zone_num` an `Option` but `offset_str` isn't? What does it mean when `zone_num` is `None`?

**Comment by twitchax** [comment]
> Is friendly_name the IANA TZ identifier?

Yes, I can add this to the docs.

> Why is friendly_name an Option? What does it mean when it is None?

There are multiple places that are considered a timezone that do not have an identifier; e.g., surrounding bases in Antarctica.

> What is zone_str? Is it just zone_num as a string and if so why does it's example value differ from zone_num?

Honestly, for now, I am just passing this through from the underlying dataset.  I'm not sure why they differ.  Doing more research.

> Why is zone_num an Option but offset_str isn't? What does it mean when zone_num is None?

This is a bug: fixing.

**Comment by twitchax** [comment]
Fixed the bug, and clarified fields.
