### ISSUE TITLE
Use more up-to-date timezone data

### ISSUE THREAD

**Issue by phayes** [twitchax/rtz#5]
The current data, coming from Natural Earth (which in turns pulls from the CIA Factbook May 2012).   This means the current data is about a decade out-of-date.

Instead, you should probably use https://github.com/evansiroky/timezone-boundary-builder, which is constantly kept up-to-date on an ongoing basis.

**Comment by twitchax** [comment]
I actually think there is a good distinction here.

Natural Earth Data _started_ with the CIA Factbook May 2012, but it has been updated continually, with the latest being last year.  There is a difference between the time zone polygons, and the _effective_ (with DST) time zone polygons / information.  NED, I believe, has up-to-date time zone polygons, but I think TBB has the _effective_ time zone polygons and information.  Might be a good idea to move, but I want to do some more research first.

**Comment by twitchax** [comment]
Actually, I kind of like the idea of doing both, and they can just be behind different feature flags, depending on use case and needs.

**Comment by twitchax** [comment]
Ok, just completely refactored to support other datasets via feature flags.  Will work on the OSM data tomorrow, and see how it goes.

**Comment by muja** [comment]
one thing I've noticed (not sure if the underlying data is at fault), is that the friendly name isn't really that friendly as you use one friendly name for all identical timezones. The example from the README returns `Europe/Mariehamn` but so do all the other coordinates of all the other countries in that timezone. Whereas other libraries give more granular friendly name, e.g. `40.4595/36.5858` (inside Türkiye) returns `Europe/Istanbul` for a library that uses the mentioned data source.

**Comment by twitchax** [comment]
Yeah, I'll be honest, that's a data source difference.  Working on incorporating OSM tonight. :)

**Comment by twitchax** [comment]
Ok, I’ve successfully ingested the OSM data.  I will deploy new versions today.

**Comment by twitchax** [comment]
Ok, shipped!
